#!/bin/sh
#
#    sens_update_rrd -
#	Update a sensors rrd database.
#	Sample usage:
#		sens_update_rrd /var/lib/database.rrd hwmon0
#
#################################################################
#
#    Copyright (c) 2014 Freescale Semiconductor, Inc. All rights reserved.
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#    MA 02110-1301 USA.
#
#################################################################
#
if [ $# -lt 1 -o $# -gt 2 ]
then
	echo "usage: $0 database.rrd [hwmonN]"
	exit 1
elif [ $# -eq 2 ]
then
	HWMON=$2
else
	HWMON=hwmon0
fi
#
RRDPATH=/usr/bin
RRDB=$1

SENSDIR=/sys/class/hwmon
SENS=$SENSDIR/$HWMON/device

if [ ! -d $SENS ]
then
	echo "No sensors found in: $SENS"
	echo "(modprobe sensor modules?)"
	exit 1
fi

STRING=N
