#!/bin/sh
#
#    sens_update_rrd -
#	Update a sensors rrd database.
#	Sample usage:
#		sens_update_rrd /var/lib/database.rrd hwmon0
#	Sample cron entry:
#		*/5 * * * * /usr/local/bin/sens_update_rrd /var/lib/sensors-rrd/sensors.rrd hwmon0
#
#################################################################
#
#    Copyright (c) 2014 Freescale Semiconductor, Inc. All rights reserved.
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#    MA 02110-1301 USA.
#
#################################################################
#
if [ $# -lt 1 -o $# -gt 2 ]
then
	echo "usage: $0 database.rrd [hwmonN]"
	exit 1
elif [ $# -eq 2 ]
then
	HWMON=$2
else
	HWMON=hwmon0
fi
#
RRDPATH=/usr/bin
RRDB=$1

SENSDIR=/sys/class/hwmon
SENS=$SENSDIR/$HWMON/device

if [ ! -d $SENS ]
then
	echo "No sensors found in: $SENS"
	echo "(modprobe sensor modules?)"
	exit 1
fi

STRING=N

#
# Get the CPU voltage value from ina220
#
SENSORS="in1"
for i in $SENSORS
do
	V="`cat $SENS/${i}_input 2> /dev/null`"
	if [ $? -ne 0 ]
	then
		STRING="${STRING}:U"
	else
		V=`echo "3k0 ${V/-/_} 1000/p"|dc`
		STRING="${STRING}:${V}"
	fi
done

#
# Get the CPU current value from ina220@CPU ph1~ph4
#
SENSORS="curr1"
for i in $SENSORS
do
	V1="`cat $SENSDIR/HWMON_CPU1/device/${i}_input 2> /dev/null`"
	V3="`cat $SENSDIR/HWMON_CPU2/device/${i}_input 2> /dev/null`"
	V4="`cat $SENSDIR/HWMON_CPU3/device/${i}_input 2> /dev/null`"
	V5="`cat $SENSDIR/HWMON_CPU4/device/${i}_input 2> /dev/null`"
	if [ $? -ne 0 ]
	then
		STRING="${STRING}:U"
	else
		V=`echo "3k0 ${V1/-/_} 1000 / ${V3/-/_} 1000 / ${V4/-/_} 1000 / ${V5/-/_} 1000 / + + + p"|dc`
		STRING="${STRING}:${V}"
	fi
done

#
# Get the first value from these /proc files
#
SENSORS="loadavg"
for i in $SENSORS
do
	V="`cat /proc/$i 2> /dev/null`"
	if [ $? -ne 0 ]
	then
		STRING="${STRING}:U"
	else
		V="`echo $V | cut -d ' ' -f 1`"
		STRING="${STRING}:${V}"
	fi
done

$RRDPATH/rrdtool update $RRDB $STRING
